#!/bin/bash

#### MONITORS ####
bspc monitor -d 1 2 3 4 5 6 7 8 9

external_monitor=$(xrandr --query | grep 'HDMI-1-2')

if [[ $external_monitor = HDMI-1-2\ connected* ]]; then
    xrandr --output eDP-1-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-2 --mode 1920x1080 --rotate normal --left-of eDP-1-1
    bspc monitor HDMI-1-2 -d 1 2 3 4
    bspc monitor eDP-1-1 -d 5 6 7 8 9
else
    xrandr --output DP-2 --auto
    bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
fi

# Truncate a couple of common commands that are used herein.
_bc() {
    bspc config "$@"
}

#### BSPWM configuration ####
_bc window_gap                    3
_bc top_padding                   26
_bc top_monocle_padding           0
_bc border_width                  1
_bc bottom_padding                0
_bc left_padding                  0
_bc right_padding                 0
_bc single_monocle                false
_bc click_to_focus                false
_bc split_ratio                   0.50
_bc borderless_monocle            true
_bc gapless_monocle               true
_bc focus_by_distance             true
_bc paddingless_monocle           true
_bc focus_follows_pointer         true
_bc ignore_ewmh_focus             true
_bc history_aware_focus           true
_bc remove_disabled_monitors      true
_bc merge_overlapping_monitors    true
_bc pointer_follows_monitor       true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner

# Colors
bspc config active_border_color   "#474f54"
bspc config focused_border_color  "#474f54"
bspc config normal_border_color   "#373d41"
bspc config presel_feedback_color "#373d41"

bspc config pointer_motion_interval 17

# Rules

bspc rule -a discord desktop=2
bspc rule -a Tixati desktop=3
bspc rule -a Steam desktop=4
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a *:SPLASH state=floating
bspc rule -a NoiseTorch state=floating
bspc rule -a net-runelite-client-RuneLite state=floating
bspc rule -a net-runelite-launcher-Launcher state=floating
bspc rule -a '*:*:Picture-in-Picture' state=floating
bspc desktop -f 1
bspc config external_rules_command "$(which windowrules)"

# INIT-DAEMONS
sxhkd &
picom --experimental-backends &
dunst &

setxkbmap -option caps:backspace
xsetroot -cursor_name left_ptr

# AUTOSTART
# set wallpaper using hsetroot
feh --bg-fill --randomize /home/cody/Pictures/blue_green.png
~/.config/bspwm/autostart &
