export XDG_RUNTIME_DIR=/run/user/$UID
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache
export XCURSOR_PATH=/usr/share/icons:$XDG_DATA_HOME/icons
export XCURSOR_SIZE=24
export XCURSOR_THEME=everforest-cursors

export PATH=${PATH}":$HOME/.local/scripts:/usr/local/go/bin:$XDG_DATA_HOME/cargo/bin:$XDG_DATA_HOME/cargo/env"

export EDITOR="nvim"
export SHELL="zsh"
export PAGER=most man ls
export BROWSER=zen-browser

# [ "$(tty)" = "/dev/tty1" ] && exec systemd-cat --identifier=sway sway
# [ "$(tty)" = "/dev/tty1" ] && exec hyprland 
